{"time":"2025-03-28T14:56:13.0842711+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\Asus\\Downloads\\Call_Agent_AI-demo_alpha\\Call_Agent_AI-demo\\backend\\wandb\\run-20250328_145612-5ki59nup\\logs\\debug-core.log"}
{"time":"2025-03-28T14:56:13.2047819+05:30","level":"INFO","msg":"created new stream","id":"5ki59nup"}
{"time":"2025-03-28T14:56:13.2047819+05:30","level":"INFO","msg":"stream: started","id":"5ki59nup"}
{"time":"2025-03-28T14:56:13.2047819+05:30","level":"INFO","msg":"handler: started","stream_id":"5ki59nup"}
{"time":"2025-03-28T14:56:13.2047819+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"5ki59nup"}
{"time":"2025-03-28T14:56:13.2053258+05:30","level":"INFO","msg":"sender: started","stream_id":"5ki59nup"}
{"time":"2025-03-28T14:56:13.7980884+05:30","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-28T14:59:03.2979196+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.13.16:53780->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T14:59:05.8504333+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/bisalprasad2003-nit-silchar/rag-pipeline/5ki59nup/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T14:59:26.3739746+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T14:59:28.8798735+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/bisalprasad2003-nit-silchar/rag-pipeline/5ki59nup/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T14:59:51.6034504+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T14:59:54.6867492+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/bisalprasad2003-nit-silchar/rag-pipeline/5ki59nup/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T15:04:44.3850905+05:30","level":"INFO","msg":"stream: closing","id":"5ki59nup"}
{"time":"2025-03-28T15:04:44.3850905+05:30","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-28T15:04:44.3861377+05:30","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-28T15:04:46.4957145+05:30","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-28T15:04:46.9715466+05:30","level":"INFO","msg":"handler: closed","stream_id":"5ki59nup"}
{"time":"2025-03-28T15:04:46.9718985+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"5ki59nup"}
{"time":"2025-03-28T15:04:46.9718985+05:30","level":"INFO","msg":"sender: closed","stream_id":"5ki59nup"}
{"time":"2025-03-28T15:04:46.9718985+05:30","level":"INFO","msg":"stream: closed","id":"5ki59nup"}
